baseURL = "https://peterdemirdjian.com"
languageCode = "en-US"
title = "Pete Demirdjian"
enableRobotsTXT = true
enableEmoji = true

[params]
  description = "Personal website and resume of Pete Demirdjian, Principal DevOps Engineer"
  twitterID = "@pdemirdjian"

[params.person]
  name = "Peter Demirdjian"
  shortName = "Pete Demirdjian"
  jobTitle = "Principal DevOps Engineer"
  employer = "CarGurus"
  school = "Northeastern University"
  email = "code@peterdemirdjian.com"
  phone = "(857) 895-2304"
  linkedin = "https://www.linkedin.com/in/peter-demirdjian/"
  github = "https://github.com/pdemirdjian/peterdemirdjiancom"
  image = "/images/home.png"

[sitemap]
  changeFreq = "monthly"

[markup.goldmark.renderer]
  unsafe = true

[[menus.main]]
  name = "Resume"
  url = "/resume/"
  weight = 1

[[menus.main]]
  name = "License"
  url = "/license/"
  weight = 2
